const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.2,
      numReviews: 12,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 3.8,
      numReviews: 20,
      countInStock: 10,
      description: "A popular pant",
    },
    {
      name: "Slim Pants",
      slug: "slim-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 120,
      brand: "Mavi",
      rating: 4.4,
      numReviews: 30,
      countInStock: 16,
      description: "A popular pant",
    },
    {
      name: "Skinny Pants",
      slug: "skinny-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 90,
      brand: "Levis",
      rating: 4.9,
      numReviews: 19,
      countInStock: 35,
      description: "A popular pant",
    },
  ],
};
export default data;